{% set name = "clickclick" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clickclick-{{ version }}.tar.gz
  sha256: 4a890aaa9c3990cfabd446294eb34e3dc89701101ac7b41c1bff85fc210f6d23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python >=3.8
    - six
    - flake8
    - pip
  run:
    - python >=3.8
    - click >=4.0
    - pyyaml >=3.11

test:
  imports:
    - clickclick
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://codeberg.org/hjacobs/python-clickclick
  license: Apache-2.0
  summary: 'Click utility functions'
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/zalando/python-clickclick

extra:
  recipe-maintainers:
    - rxm7706
    - rvalieris
