{% set version = "1.2.2" %}

package:
  name: clickclick
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/zalando/python-clickclick/archive/{{ version }}.tar.gz
  sha256: 641779b3578f56ab00440806088ed02b95224342544f24de99d97a506f05c457
  
build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - flake8
    - six

  run:
    - python
    - click >=4.0
    - pyyaml >=3.11

test:
  imports:
    - clickclick

about:
  home: https://github.com/zalando/python-clickclick
  license: Apache-2.0
  summary: 'Click utility functions'
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/zalando/python-clickclick

extra:
  recipe-maintainers:
    - rxm7706
    - rvalieris
